### ISSUE TITLE
ValueError: Negative dimensions are not allowed - when running m4opt schedule for certain events

### ISSUE THREAD

**Issue by weizmannk** [m4opt/m4opt#192]
Hi @lpsinger ,
I'm encountering a `ValueError` while attempting to run the **m4opt schedule** command. The error occurs during the result writing phase after successfully solving the MILP model. But  most of jobs have excecuted well , it's only 4 jobs which failed .
Below are the detailed steps, environment information, and error traceback .

1. Command line :

```
m4opt schedule /home/weizmann.kiendrebeogo/Dorado/runs/O6HLVK/farah/allsky/101.fits /home/weizmann.kiendrebeogo/M4OPT/uvex-m4opt/UVEX/schedules/101.ecsv --mission=uvex --exptime='0.5 ks' --nside=128 --delay='6hour' --deadline='24hour' --timelimit='20min' --jobs 10

```

2. ![Failed Job Screenshot](https://github.com/user-attachments/assets/af38b4ea-f6fd-4dfc-923c-3f32fef3fb12)

3- I also have failed to  calculate the HEALPix pixels  using the **schedule file** (.ecsv)  [footprint_healpix ](https://github.com/m4opt/m4opt/blob/main/m4opt/fov/_core.py#L251
)

Here my script :

```
  from m4opt.fov import _core
  from astropy.table import QTable
  from astropy_healpix import HEALPix
  from astropy.coordinates import ICRS
  
  healpix = HEALPix(64, order='nested', frame=ICRS())
  
  schedule = QTable.read('3872.ecsv', format='ascii.ecsv')
  for row in schedule:         
      indices = _core.footprint_healpix(
          healpix, row['observer_location'], row['target_coord'], row['roll']
      )
```

This raised that error:

`NotImplementedError: Footprint transformations are not implemented for MaskedEarthLocation
`

Could you please let me know how to fix these errors? 

4. Finally, I was expected to use the Ultrasat mission, but in M4OPT, only the UVEX mission is available.

 Thank you

**Comment by lpsinger** [comment]
> Hi @lpsinger , I'm encountering a `ValueError` while attempting to run the **m4opt schedule** command. The error occurs during the result writing phase after successfully solving the MILP model. But most of jobs have excecuted well , it's only 4 jobs which failed . Below are the detailed steps, environment information, and error traceback .
>
> 3- I also have failed to calculate the HEALPix pixels using the **schedule file** (.ecsv) [footprint_healpix ](https://github.com/m4opt/m4opt/blob/main/m4opt/fov/_core.py#L251)
> 
> Here my script :
> 
> ```
>   from m4opt.fov import _core
>   from astropy.table import QTable
>   from astropy_healpix import HEALPix
>   from astropy.coordinates import ICRS
>   
>   healpix = HEALPix(64, order='nested', frame=ICRS())
>   
>   schedule = QTable.read('3872.ecsv', format='ascii.ecsv')
>   for row in schedule:         
>       indices = _core.footprint_healpix(
>           healpix, row['observer_location'], row['target_coord'], row['roll']
>       )
> ```
> 
> This raised that error:
> 
> `NotImplementedError: Footprint transformations are not implemented for MaskedEarthLocation `
> 
> Could you please let me know how to fix these errors?

These two issues may have the same root cause. I'm taking a look. But meanwhile, are a few suggestions for your script:

- Modules with names starting with an underscore are considered "internal" and are not part of the public interface, so their API may change at any time. Instead of `from m4opt.fov import _core; _core.footprint_healpix` use `from m4opt import fov; fov.footprint_healpix`.
- The method `m4opt.fov.footprint_healpix` is vectorized. You will get faster results if you call it like this:

```python
for indices in fov.footprint_healpix(healpix, schedule['observer_lcoation'], schedule['target_coord'], schedule['roll']:
    ... # do something with indices here
```

> 4. Finally, I was expected to use the Ultrasat mission, but in M4OPT, only the UVEX mission is available.

No one has added it yet. Patches are welcome!

**Comment by lpsinger** [comment]
These are four separate problems. In the future, please open separate issues for each problem.

> Hi @lpsinger , I'm encountering a `ValueError` while attempting to run the **m4opt schedule** command. The error occurs during the result writing phase after successfully solving the MILP model. But most of jobs have excecuted well , it's only 4 jobs which failed . Below are the detailed steps, environment information, and error traceback .
> 
> 1. Command line :
> 
> ```
> m4opt schedule /home/weizmann.kiendrebeogo/Dorado/runs/O6HLVK/farah/allsky/101.fits /home/weizmann.kiendrebeogo/M4OPT/uvex-m4opt/UVEX/schedules/101.ecsv --mission=uvex --exptime='0.5 ks' --nside=128 --delay='6hour' --deadline='24hour' --timelimit='20min' --jobs 10
> ```

Please attach a copy of the FITS file.

> 3- I also have failed to calculate the HEALPix pixels using the **schedule file** (.ecsv) [footprint_healpix ](https://github.com/m4opt/m4opt/blob/main/m4opt/fov/_core.py#L251)
> 
> Here my script :
> 
> ```
>   from m4opt.fov import _core
>   from astropy.table import QTable
>   from astropy_healpix import HEALPix
>   from astropy.coordinates import ICRS
>   
>   healpix = HEALPix(64, order='nested', frame=ICRS())
>   
>   schedule = QTable.read('3872.ecsv', format='ascii.ecsv')
>   for row in schedule:         
>       indices = _core.footprint_healpix(
>           healpix, row['observer_location'], row['target_coord'], row['roll']
>       )
> ```
> 
> This raised that error:
> 
> `NotImplementedError: Footprint transformations are not implemented for MaskedEarthLocation `
> 
> Could you please let me know how to fix these errors?

You're not calling the function with valid arguments. According to the [documentation](https://m4opt.readthedocs.io/en/latest/api/m4opt.fov.footprint_healpix.html#m4opt.fov.footprint_healpix), the function signature is:

```
def footprint_healpix(
    hpx: HEALPix,
    region: Region | Regions,
    target_coord: SkyCoord,
    rotation: u.Quantity[u.physical.angle] | None = None,
):
```
 
> 4. Finally, I was expected to use the Ultrasat mission, but in M4OPT, only the UVEX mission is available.

I opened a separate issue for that (#193). Patches are welcome!

**Comment by weizmannk** [comment]
@lpsinger  Thank you so.  
I reviewed the script, and I can now calculate the indices.
 I have attached the .fits file, here : https://github.com/weizmannk/ObservingScenariosInsights/blob/main/readSkymap/101.fits

**Comment by lpsinger** [comment]
Reported to Astropy as astropy/astropy#17378.

**Comment by lpsinger** [comment]
Also https://github.com/astropy/astropy/issues/17379.
