### ISSUE TITLE
Background noise discrepancy between uvex-mission algorithm and the M4OPT process

### ISSUE THREAD

**Issue by weizmannk** [m4opt/m4opt#209]
Hi @lpsinger 

I tried to determine the background noise of the uvex-mission. My goal was to obtain results similar to those I got using the uvex-mission (the same method Alexander used for his paper). By "uvex-mission" I mean the algorithm using for the  UVEX follow-up.
For a quick test, I computed the total background  (galactic and zodiacal) using the uvex-mission algorithm: **0.04938998431822868 ct/s** .

However, when using the M4OPT process, I obtained **0.021225372163088327 ct/s**, which is at least half the value of the previous result.
I suspect I may have misused something, but unfortunately, I couldn't identify the source of the problem.
Could you please let me know how to fix this?

Here is my script:

```
import healpy as hp
import numpy as np
from astropy import units as u
from astropy.time import Time
from astropy.coordinates import ICRS, SkyCoord, EarthLocation
from astropy_healpix import HEALPix

from synphot import Observation

from m4opt.missions import uvex
from m4opt.models.background import GalacticBackground, ZodiacalBackground
from m4opt.models import observing


obstime = Time('2012-03-25T15:14:21.278')
nside = 64  # HEALPix resolution
ipix = 12290  # Pixel index

# Get the angular coordinates from the HEALPix pixel
theta, phi = hp.pix2ang(nside, ipix, nest=True)
ra = np.rad2deg(phi)  # Convert from radians to degrees
dec = np.rad2deg(0.5 * np.pi - theta)  # Convert from radians to degrees

# Create a SkyCoord object with the RA and Dec
sky_coord = SkyCoord(ra=ra * u.deg, dec=dec * u.deg, frame='icrs', obstime=obstime)

observer_location = EarthLocation(0 * u.m, 0 * u.m, 0 * u.m) 

# Bandpass and area for the UVEX mission
area = uvex.detector.area
bandpass = uvex.detector.bandpasses['NUV']

# Convert the target coordinates to Galactic coordinates
gal_coord = sky_coord.galactic

# Calculate Galactic background noise
with observing(
    observer_location=observer_location,
    target_coord=gal_coord, 
   obstime=obstime
): 
    galac_noise = Observation(GalacticBackground(), bandpass)

# Calculate Zodiacal background noise
with observing(
    observer_location=observer_location, 
    target_coord=sky_coord, 
   obstime=obstime
):
    zod_noise = Observation(ZodiacalBackground(), bandpass)

# Total count rate from both backgrounds
print(zod_noise.countrate(area=area) + galac_noise.countrate(area=area))

```

Thank you.

**Comment by lpsinger** [comment]
I have only half of the information that I would need here to reproduce this. What, exactly, do you mean by "the vex-mission algorithm"? And where is the code to reproduce it?

**Comment by weizmannk** [comment]
Hi @lpsinger ,
By "uvex-mission algorithm," I mean the private repository: [uvex-mission)]( https://github.com/uvex-mission/uvex-mission). 

Here is the script, which gives 0.04938998431822868 ct/s for the total.

```
import healpy as hp
import numpy as np
from astropy import units as u
from astropy.coordinates import ICRS, SkyCoord
from astropy.time import Time
from synphot import Observation, SourceSpectrum
from synphot.models import ConstFlux1D

from uvex.sensitivity import galactic, zodi
from m4opt.missions import uvex as UVex
from m4opt.models.background import GalacticBackground, ZodiacalBackground

# Telescope parameters
area = UVex.detector.area  # detector area in cm^2
bandpass = UVex.detector.bandpasses['NUV'] 

# Observation parameters
obstime = Time('2024-01-01 00:00:00')
nside = 64  # Healpix resolution
ipix = 12290  # Healpix pixel index
m_obs = 28.310335426912324  # AB magnitude 

# Convert HEALPix index to sky coordinates
theta, phi = hp.pix2ang(nside, ipix, nest=True)
ra = np.rad2deg(phi)
dec = np.rad2deg(0.5 * np.pi - theta)
sky_coord = SkyCoord(ra=ra * u.deg, dec=dec * u.deg, frame=ICRS, obstime=obstime)

# Galactic background
gal_coord = sky_coord.galactic
galactic_spec = galactic.galactic_nuv_spec(gal_coord.b)  # Galactic spectrum
galactic_obs = Observation(galactic_spec, bandpass)  # Observation with bandpass

# Zodiacal background
zodi_spec = zodi.zodi_spec_coords(sky_coord, obstime, diag=False)  # Zodiacal spectrum
zodi_obs = Observation(zodi_spec, bandpass)  # Observation with bandpass

# Calculate total sky background
sky_back = zodi_obs.countrate(area=area) + galactic_obs.countrate(area=area)
print(sky_back)

# # Calculate source count rate
# source_spectrum = SourceSpectrum(ConstFlux1D, amplitude=m_obs * u.ABmag)
# observation = Observation(source_spectrum, bandpass)
# source_rate = observation.countrate(area=area)
# obstime = Time('2012-03-25T15:14:21.278')

# texp = uvex.sensitivity.get_exposure(source_rate, sky_back)

```

**Comment by lpsinger** [comment]
Well, there are any number of reasons that these two codes might give different results. The uvex-mission code performs linear interpolation of the spatial dependence of zodiacal light in SI surface brightness units, whereas m4opt does the interpolation in logarithmic units. The latter will have better numerical accuracy.

Also the bandpass models don't match up exactly.

**Comment by weizmannk** [comment]
@lpsinger  , I got it. Thank you for the explanation.
Here is what I used to determine the exposure time, as this was what I was looking for.

import healpy as hp
import numpy as np
from astropy import units as u
from astropy.time import Time
from astropy.coordinates import ICRS, SkyCoord, EarthLocation
from astropy_healpix import HEALPix

from synphot import Observation
from synphot import ConstFlux1D, SourceSpectrum
from m4opt.missions import uvex
from m4opt.models.background import GalacticBackground, ZodiacalBackground
from m4opt.models import observing

# Observation parameters
obstime = Time('2024-01-01 00:00:00')
nside = 64  # Healpix resolution
ipix = 12290  # Healpix pixel index
m_obs = 28.310335426912324  # AB magnitude 
SNR=5.

theta, phi = hp.pix2ang(nside, ipix, nest=True)
ra = np.rad2deg(phi)
dec = np.rad2deg(0.5 * np.pi - theta)
sky_coord  = SkyCoord(ICRS(ra=ra * u.deg, dec=dec * u.deg), obstime=obstime)

observer_location = EarthLocation(0 * u.m, 0 * u.m, 0 * u.m)

with observing(
    observer_location=observer_location,
    target_coord=sky_coord,
    obstime=obstime,
):
    texp = uvex.detector.get_exptime(
        snr = SNR, 
        source_spectrum=SourceSpectrum(ConstFlux1D, amplitude=m_obs * u.ABmag),
        bandpass='NUV' 
    )
        
print('exposure time: ', texp)

**Comment by lpsinger** [comment]
What do you want me to do with this issue? Is there some action to take here?

**Comment by weizmannk** [comment]
I think we can close as complete . I just left the script as an example. Maybe this can be useful to someone else.
