### ISSUE TITLE
Optimal Parameters for ULTRASAT Scheduling (deadline and the dealine) 

### ISSUE THREAD

**Issue by weizmannk** [m4opt/m4opt#250]
Hi @lpsinger,

I have completed the ULTRASAT simulation process, and everything works fine.
Now, I want to use the appropriate values based on ULTRASAT's capabilities.
For the test, I used the following command for scheduling: 
```
m4opt schedule ./2313.fits ./2313.ecsv --mission=ultrasat --exptime='1.7025111654060896 ks' --nside=128 --delay='6 hr' --deadline='24 hr' --timelimit='20min' --jobs 0
```
However, I have some doubts about the values for `--delay='6 hr'` and `--deadline='24 hr'`.
ULTRASAT is expected to launch in 2027, so does the `--delay `parameter refer to a two-year delay, or does it mean the time until the source becomes visible, here the kilonova event. 

I am wondering if these values are optimal for ULTRASAT. Could you please suggest the more accurate values,
to be use. 

Thank you so

**Comment by lpsinger** [comment]
> However, I have some doubts about the values for `--delay='6 hr'` and `--deadline='24 hr'`. ULTRASAT is expected to launch in 2027, so does the `--delay `parameter refer to a two-year delay, or does it mean the time until the source becomes visible, here the kilonova event.

The latter.

**Comment by weizmannk** [comment]
Hi @lpsinger ,
We already discussed the `--delay=6 hr`, which is supposed to be the time before the kilonova event becomes visible in the UV. Michael would like to know if, for ULTRASAT, we could change this value to 15 minutes, which corresponds to the time ULTRASAT will be able to start observations at any visible position from an incoming alert.

So, do you think it is doable to set `--delay=15 min` instead of 6 hours?

Thanks

**Comment by lpsinger** [comment]
Why are you asking this on a GitHub issue? The delay time is a command line argument and you can set it to whatever you like. There's no code change to make here.

**Comment by mcoughlin** [comment]
@lpsinger i think the question just comes down to the correct interpretation of the variable. It sounds like we do understand how we are using it though, eg the assumed delay until schedule upload is possible.

**Comment by lpsinger** [comment]
I see. It's documented like this:

```
$ m4opt schedule --help | grep delay
│ --delay                 ASTROPY QUANTITY       Delay from time of event until the start of observations [default: 0 day]          
```

The use case that I had in mind is that you may want to simulate the situation where there is some latency between the time of the event and the time that the commands make it to the spacecraft. But the effect is the following. The sky map must contain a `DATE-OBS` card that states the time of the event. The scheduler will plan observations from a time `DATE_OBS + delay` to `DATE-OBS + deadline`.

What changes do we need to make to the [command line help](https://m4opt.readthedocs.io/en/latest/guide/cli.html#m4opt-schedule) so that this is clear?

**Comment by mcoughlin** [comment]
@lpsinger. The command line is alright, maybe eventually can be a page where a sample observing scenarios is simulated and a sentence can be mentioned for the numbers we have assumed for UVEX and ULTRASAT?
